[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$skillsRoot = Join-Path $repoRoot 'skills'
$agentsRoot = Join-Path $repoRoot 'agents'
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

function Get-FrontmatterValue {
    param(
        [Parameter(Mandatory)] [string] $Content,
        [Parameter(Mandatory)] [string] $Key
    )

    $match = [regex]::Match($Content, "(?m)^$([regex]::Escape($Key)):\s*(.+?)\s*$")
    if (-not $match.Success) { return '' }
    return $match.Groups[1].Value.Trim().Trim('"').Trim("'")
}

function Get-TomlValue {
    param(
        [Parameter(Mandatory)] [string] $Content,
        [Parameter(Mandatory)] [string] $Key
    )

    $pattern = '(?m)^' + [regex]::Escape($Key) + '\s*=\s*"([^"]*)"\s*$'
    $match = [regex]::Match($Content, $pattern)
    if (-not $match.Success) { return '' }
    return $match.Groups[1].Value
}

$skills = Get-ChildItem -LiteralPath $skillsRoot -Directory | Sort-Object Name | ForEach-Object {
    $skillFile = Join-Path $_.FullName 'SKILL.md'
    $content = [System.IO.File]::ReadAllText($skillFile)
    $files = Get-ChildItem -LiteralPath $_.FullName -Recurse -File -Force
    $licenseNames = Get-ChildItem -LiteralPath $_.FullName -File -Force |
        Where-Object { $_.Name -match '^(LICENSE|COPYING|NOTICE)(\..+)?$' } |
        Select-Object -ExpandProperty Name

    [ordered]@{
        name = Get-FrontmatterValue -Content $content -Key 'name'
        description = Get-FrontmatterValue -Content $content -Key 'description'
        path = "skills/$($_.Name)"
        files = @($files).Count
        bytes = [long](($files | Measure-Object -Property Length -Sum).Sum)
        licenses = @($licenseNames)
    }
}

$agents = Get-ChildItem -LiteralPath $agentsRoot -Filter '*.toml' -File | Sort-Object Name | ForEach-Object {
    $content = [System.IO.File]::ReadAllText($_.FullName)
    [ordered]@{
        name = Get-TomlValue -Content $content -Key 'name'
        description = Get-TomlValue -Content $content -Key 'description'
        path = "agents/$($_.Name)"
        reasoning_effort = Get-TomlValue -Content $content -Key 'model_reasoning_effort'
        sandbox_mode = Get-TomlValue -Content $content -Key 'sandbox_mode'
    }
}

$catalog = [ordered]@{
    version = 1
    updated_at = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd')
    skills = @($skills)
    agents = @($agents)
}

$json = $catalog | ConvertTo-Json -Depth 8
[System.IO.File]::WriteAllText((Join-Path $repoRoot 'catalog.json'), "$json`n", $utf8NoBom)

$markdown = [System.Collections.Generic.List[string]]::new()
$markdown.Add('# Catalog')
$markdown.Add('')
$markdown.Add("Generated by ``scripts/build-catalog.ps1``. Skills: $($skills.Count). Agents: $($agents.Count).")
$markdown.Add('')
$markdown.Add('## Agents')
$markdown.Add('')
$markdown.Add('| Agent | Purpose | Reasoning | Sandbox |')
$markdown.Add('|---|---|---|---|')
foreach ($agent in $agents) {
    $markdown.Add("| [$($agent.name)]($($agent.path)) | $($agent.description.Replace('|', '\|')) | $($agent.reasoning_effort) | $($agent.sandbox_mode) |")
}
$markdown.Add('')
$markdown.Add('## Skills')
$markdown.Add('')
$markdown.Add('| Skill | Purpose | Files | License |')
$markdown.Add('|---|---|---:|---|')
foreach ($skill in $skills) {
    $licenseText = if ($skill.licenses.Count) { $skill.licenses -join ', ' } else { 'not specified in folder' }
    $markdown.Add("| [$($skill.name)]($($skill.path)/SKILL.md) | $($skill.description.Replace('|', '\|')) | $($skill.files) | $licenseText |")
}
[System.IO.File]::WriteAllText((Join-Path $repoRoot 'CATALOG.md'), (($markdown -join "`n") + "`n"), $utf8NoBom)

Write-Output "Built catalog for $($skills.Count) skills and $($agents.Count) agents."
